<<<<<<< HEAD
-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 11:27:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quimic_lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quimic_lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quimic_lab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `quimic_lab` ;

-- -----------------------------------------------------
-- Table `quimic_lab`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `tipo` ENUM('aluno', 'professor') NOT NULL,
  `turma` VARCHAR(50) NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ordem` TINYINT NOT NULL,
  `pontuacao_minima_pct` TINYINT NOT NULL DEFAULT 60,
  `tempo_limite_seg` SMALLINT NOT NULL DEFAULT 120,
  PRIMARY KEY (`id_nivel`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`pergunta` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `id_nivel` INT NOT NULL,
  `id_criador` INT NULL DEFAULT NULL,
  `enunciado` TEXT NOT NULL,
  `imagem_url` VARCHAR(500) NULL DEFAULT NULL,
  `ativa` TINYINT(1) NOT NULL DEFAULT 1,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_perg_nivel` (`id_nivel` ASC) VISIBLE,
  INDEX `fk_perg_criador` (`id_criador` ASC) VISIBLE,
  CONSTRAINT `fk_perg_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`),
  CONSTRAINT `fk_perg_criador`
    FOREIGN KEY (`id_criador`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`alternativa` (
  `id_alternativa` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `texto` TEXT NULL DEFAULT NULL,
  `imagem_url` VARCHAR(500) NULL DEFAULT NULL,
  `correta` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_alternativa`),
  INDEX `fk_alt_pergunta` (`id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_alt_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`dica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`dica` (
  `id_dica` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `tipo` ENUM('eliminacao', 'texto') NOT NULL,
  `conteudo` TEXT NOT NULL,
  `penalizacao_pontos` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_dica`),
  INDEX `fk_dica_perg` (`id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_dica_perg`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`sessao_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`sessao_jogo` (
  `id_sessao` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  `pontuacao` SMALLINT NOT NULL DEFAULT 0,
  `concluida` TINYINT(1) NOT NULL DEFAULT 0,
  `iniciado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finalizado_em` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_sessao`),
  INDEX `fk_sess_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_sess_nivel` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_sess_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_sess_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`resposta` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `id_sessao` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `id_alternativa_escolhida` INT NOT NULL,
  `correta` TINYINT(1) NOT NULL,
  `tempo_resposta_seg` SMALLINT NULL DEFAULT NULL,
  `feedback_exibido` TINYINT(1) NOT NULL DEFAULT 0,
  `respondido_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resposta`),
  INDEX `fk_resp_sessao` (`id_sessao` ASC) VISIBLE,
  INDEX `fk_resp_pergunta` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_resp_alternativa` (`id_alternativa_escolhida` ASC) VISIBLE,
  CONSTRAINT `fk_resp_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `quimic_lab`.`sessao_jogo` (`id_sessao`),
  CONSTRAINT `fk_resp_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`),
  CONSTRAINT `fk_resp_alternativa`
    FOREIGN KEY (`id_alternativa_escolhida`)
    REFERENCES `quimic_lab`.`alternativa` (`id_alternativa`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`uso_dica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`uso_dica` (
  `id_uso_dica` INT NOT NULL AUTO_INCREMENT,
  `id_sessao` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `id_dica` INT NOT NULL,
  `usado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_uso_dica`),
  INDEX `fk_uso_sessao` (`id_sessao` ASC) VISIBLE,
  INDEX `fk_uso_pergunta` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_uso_dica_ref` (`id_dica` ASC) VISIBLE,
  CONSTRAINT `fk_uso_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `quimic_lab`.`sessao_jogo` (`id_sessao`),
  CONSTRAINT `fk_uso_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`),
  CONSTRAINT `fk_uso_dica_ref`
    FOREIGN KEY (`id_dica`)
    REFERENCES `quimic_lab`.`dica` (`id_dica`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`ranking` (
  `id_ranking` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  `melhor_pontuacao` SMALLINT NOT NULL DEFAULT 0,
  `total_tentativas` SMALLINT NOT NULL DEFAULT 0,
  `atualizado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ranking`),
  UNIQUE INDEX `uq_ranking` (`id_usuario` ASC, `id_nivel` ASC) VISIBLE,
  INDEX `fk_rank_nivel` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_rank_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_rank_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`));

USE `quimic_lab` ;

-- -----------------------------------------------------
-- Placeholder table for view `quimic_lab`.`vw_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`vw_desempenho` (`id_usuario` INT, `nome` INT, `turma` INT, `nivel` INT, `total_respostas` INT, `acertos` INT, `erros` INT, `tempo_medio_seg` INT, `taxa_acerto_pct` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quimic_lab`.`vw_questoes_mais_erradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`vw_questoes_mais_erradas` (`id_pergunta` INT, `enunciado` INT, `nivel` INT, `total_respostas` INT, `total_erros` INT, `taxa_erro_pct` INT);

-- -----------------------------------------------------
-- View `quimic_lab`.`vw_desempenho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quimic_lab`.`vw_desempenho`;
USE `quimic_lab`;
CREATE OR REPLACE VIEW vw_desempenho AS
SELECT
    u.id_usuario,
    u.nome,
    u.turma,
    n.nome                              AS nivel,
    COUNT(r.id_resposta)                AS total_respostas,
    SUM(r.correta)                      AS acertos,
    COUNT(r.id_resposta) - SUM(r.correta) AS erros,
    ROUND(AVG(r.tempo_resposta_seg), 1) AS tempo_medio_seg,
    ROUND(SUM(r.correta) * 100.0
          / NULLIF(COUNT(r.id_resposta), 0), 1) AS taxa_acerto_pct
FROM usuario u
JOIN sessao_jogo s  ON s.id_usuario = u.id_usuario
JOIN nivel n        ON n.id_nivel   = s.id_nivel
JOIN resposta r     ON r.id_sessao  = s.id_sessao
GROUP BY u.id_usuario, u.nome, u.turma, n.id_nivel, n.nome;

-- -----------------------------------------------------
-- View `quimic_lab`.`vw_questoes_mais_erradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quimic_lab`.`vw_questoes_mais_erradas`;
USE `quimic_lab`;
CREATE OR REPLACE VIEW vw_questoes_mais_erradas AS
SELECT
    p.id_pergunta,
    p.enunciado,
    n.nome                                              AS nivel,
    COUNT(r.id_resposta)                                AS total_respostas,
    SUM(CASE WHEN r.correta = 0 THEN 1 ELSE 0 END)     AS total_erros,
    ROUND(SUM(CASE WHEN r.correta = 0 THEN 1 ELSE 0 END)
          * 100.0 / NULLIF(COUNT(r.id_resposta), 0), 1) AS taxa_erro_pct
FROM pergunta p
JOIN nivel n      ON n.id_nivel     = p.id_nivel
JOIN resposta r   ON r.id_pergunta  = p.id_pergunta
GROUP BY p.id_pergunta, p.enunciado, n.id_nivel, n.nome
ORDER BY taxa_erro_pct DESC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 11:27:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quimic_lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quimic_lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quimic_lab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `quimic_lab` ;

-- -----------------------------------------------------
-- Table `quimic_lab`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `tipo` ENUM('aluno', 'professor') NOT NULL,
  `turma` VARCHAR(50) NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ordem` TINYINT NOT NULL,
  `pontuacao_minima_pct` TINYINT NOT NULL DEFAULT 60,
  `tempo_limite_seg` SMALLINT NOT NULL DEFAULT 120,
  PRIMARY KEY (`id_nivel`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`pergunta` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `id_nivel` INT NOT NULL,
  `id_criador` INT NULL DEFAULT NULL,
  `enunciado` TEXT NOT NULL,
  `imagem_url` VARCHAR(500) NULL DEFAULT NULL,
  `ativa` TINYINT(1) NOT NULL DEFAULT 1,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_perg_nivel` (`id_nivel` ASC) VISIBLE,
  INDEX `fk_perg_criador` (`id_criador` ASC) VISIBLE,
  CONSTRAINT `fk_perg_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`),
  CONSTRAINT `fk_perg_criador`
    FOREIGN KEY (`id_criador`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`alternativa` (
  `id_alternativa` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `texto` TEXT NULL DEFAULT NULL,
  `imagem_url` VARCHAR(500) NULL DEFAULT NULL,
  `correta` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_alternativa`),
  INDEX `fk_alt_pergunta` (`id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_alt_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`dica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`dica` (
  `id_dica` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `tipo` ENUM('eliminacao', 'texto') NOT NULL,
  `conteudo` TEXT NOT NULL,
  `penalizacao_pontos` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_dica`),
  INDEX `fk_dica_perg` (`id_pergunta` ASC) VISIBLE,
  CONSTRAINT `fk_dica_perg`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`sessao_jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`sessao_jogo` (
  `id_sessao` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  `pontuacao` SMALLINT NOT NULL DEFAULT 0,
  `concluida` TINYINT(1) NOT NULL DEFAULT 0,
  `iniciado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finalizado_em` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_sessao`),
  INDEX `fk_sess_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_sess_nivel` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_sess_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_sess_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`resposta` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `id_sessao` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `id_alternativa_escolhida` INT NOT NULL,
  `correta` TINYINT(1) NOT NULL,
  `tempo_resposta_seg` SMALLINT NULL DEFAULT NULL,
  `feedback_exibido` TINYINT(1) NOT NULL DEFAULT 0,
  `respondido_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resposta`),
  INDEX `fk_resp_sessao` (`id_sessao` ASC) VISIBLE,
  INDEX `fk_resp_pergunta` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_resp_alternativa` (`id_alternativa_escolhida` ASC) VISIBLE,
  CONSTRAINT `fk_resp_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `quimic_lab`.`sessao_jogo` (`id_sessao`),
  CONSTRAINT `fk_resp_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`),
  CONSTRAINT `fk_resp_alternativa`
    FOREIGN KEY (`id_alternativa_escolhida`)
    REFERENCES `quimic_lab`.`alternativa` (`id_alternativa`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`uso_dica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`uso_dica` (
  `id_uso_dica` INT NOT NULL AUTO_INCREMENT,
  `id_sessao` INT NOT NULL,
  `id_pergunta` INT NOT NULL,
  `id_dica` INT NOT NULL,
  `usado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_uso_dica`),
  INDEX `fk_uso_sessao` (`id_sessao` ASC) VISIBLE,
  INDEX `fk_uso_pergunta` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_uso_dica_ref` (`id_dica` ASC) VISIBLE,
  CONSTRAINT `fk_uso_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `quimic_lab`.`sessao_jogo` (`id_sessao`),
  CONSTRAINT `fk_uso_pergunta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `quimic_lab`.`pergunta` (`id_pergunta`),
  CONSTRAINT `fk_uso_dica_ref`
    FOREIGN KEY (`id_dica`)
    REFERENCES `quimic_lab`.`dica` (`id_dica`));


-- -----------------------------------------------------
-- Table `quimic_lab`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`ranking` (
  `id_ranking` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  `melhor_pontuacao` SMALLINT NOT NULL DEFAULT 0,
  `total_tentativas` SMALLINT NOT NULL DEFAULT 0,
  `atualizado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ranking`),
  UNIQUE INDEX `uq_ranking` (`id_usuario` ASC, `id_nivel` ASC) VISIBLE,
  INDEX `fk_rank_nivel` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `fk_rank_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `quimic_lab`.`usuario` (`id_usuario`),
  CONSTRAINT `fk_rank_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `quimic_lab`.`nivel` (`id_nivel`));

USE `quimic_lab` ;

-- -----------------------------------------------------
-- Placeholder table for view `quimic_lab`.`vw_desempenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`vw_desempenho` (`id_usuario` INT, `nome` INT, `turma` INT, `nivel` INT, `total_respostas` INT, `acertos` INT, `erros` INT, `tempo_medio_seg` INT, `taxa_acerto_pct` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quimic_lab`.`vw_questoes_mais_erradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quimic_lab`.`vw_questoes_mais_erradas` (`id_pergunta` INT, `enunciado` INT, `nivel` INT, `total_respostas` INT, `total_erros` INT, `taxa_erro_pct` INT);

-- -----------------------------------------------------
-- View `quimic_lab`.`vw_desempenho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quimic_lab`.`vw_desempenho`;
USE `quimic_lab`;
CREATE OR REPLACE VIEW vw_desempenho AS
SELECT
    u.id_usuario,
    u.nome,
    u.turma,
    n.nome                              AS nivel,
    COUNT(r.id_resposta)                AS total_respostas,
    SUM(r.correta)                      AS acertos,
    COUNT(r.id_resposta) - SUM(r.correta) AS erros,
    ROUND(AVG(r.tempo_resposta_seg), 1) AS tempo_medio_seg,
    ROUND(SUM(r.correta) * 100.0
          / NULLIF(COUNT(r.id_resposta), 0), 1) AS taxa_acerto_pct
FROM usuario u
JOIN sessao_jogo s  ON s.id_usuario = u.id_usuario
JOIN nivel n        ON n.id_nivel   = s.id_nivel
JOIN resposta r     ON r.id_sessao  = s.id_sessao
GROUP BY u.id_usuario, u.nome, u.turma, n.id_nivel, n.nome;

-- -----------------------------------------------------
-- View `quimic_lab`.`vw_questoes_mais_erradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quimic_lab`.`vw_questoes_mais_erradas`;
USE `quimic_lab`;
CREATE OR REPLACE VIEW vw_questoes_mais_erradas AS
SELECT
    p.id_pergunta,
    p.enunciado,
    n.nome                                              AS nivel,
    COUNT(r.id_resposta)                                AS total_respostas,
    SUM(CASE WHEN r.correta = 0 THEN 1 ELSE 0 END)     AS total_erros,
    ROUND(SUM(CASE WHEN r.correta = 0 THEN 1 ELSE 0 END)
          * 100.0 / NULLIF(COUNT(r.id_resposta), 0), 1) AS taxa_erro_pct
FROM pergunta p
JOIN nivel n      ON n.id_nivel     = p.id_nivel
JOIN resposta r   ON r.id_pergunta  = p.id_pergunta
GROUP BY p.id_pergunta, p.enunciado, n.id_nivel, n.nome
ORDER BY taxa_erro_pct DESC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
>>>>>>> 66ba91564e7fb655c9df26d46278a64f1a976b55
